// ABOUTME: Pre-build script that embeds viewer.html + viewer.css + viewer/*.js into a TypeScript module
// ABOUTME: Reads the HTML template, CSS, JS modules, and font woff2 files, inlines everything into a single HTML string

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';

const rootDir = join(dirname(process.argv[1]), '..');
const htmlPath = join(rootDir, 'viewer.html');
const cssPath = join(rootDir, 'viewer.css');
const jsDir = join(rootDir, 'viewer');
const outPath = join(rootDir, 'src', 'viewer-html.ts');

// ---------------------------------------------------------------------------
// Font embedding: self-host fonts as base64 data URIs for offline support
// All fonts are SIL Open Font License 1.1 — legal to bundle and redistribute
// ---------------------------------------------------------------------------
const FONTS: Array<{ family: string; pkg: string; weight: number; style: string }> = [
  // Inter (UI font for settings, sidebar, controls)
  { family: 'Inter', pkg: 'inter', weight: 400, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 500, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 600, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 700, style: 'normal' },
  // Literata (reading font option)
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 700, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'italic' },
  // Lora (reading font option)
  { family: 'Lora', pkg: 'lora', weight: 400, style: 'normal' },
  { family: 'Lora', pkg: 'lora', weight: 700, style: 'normal' },
  { family: 'Lora', pkg: 'lora', weight: 400, style: 'italic' },
  // Source Serif 4 (reading font option)
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 400, style: 'normal' },
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 700, style: 'normal' },
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 400, style: 'italic' },
  // Work Sans (primary UI font + reading font option)
  { family: 'Work Sans', pkg: 'work-sans', weight: 400, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 500, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 600, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 700, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 400, style: 'italic' },
  // Instrument Serif (title font for pairings)
  { family: 'Instrument Serif', pkg: 'instrument-serif', weight: 400, style: 'normal' },
  { family: 'Instrument Serif', pkg: 'instrument-serif', weight: 400, style: 'italic' },
  // OpenDyslexic (accessibility reading font)
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 400, style: 'normal' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 700, style: 'normal' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 400, style: 'italic' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 700, style: 'italic' },
];

function generateFontCSS(): string {
  const lines: string[] = ['/* Self-hosted fonts (all SIL OFL 1.1) — generated by embed-viewer.ts */'];
  let totalRaw = 0;
  let count = 0;

  for (const font of FONTS) {
    const filename = `${font.pkg}-latin-${font.weight}-${font.style}.woff2`;
    const filepath = join(rootDir, 'node_modules', '@fontsource', font.pkg, 'files', filename);
    if (!existsSync(filepath)) {
      console.warn(`  Warning: font file not found: ${filename} (run bun install)`);
      continue;
    }
    const data = readFileSync(filepath);
    totalRaw += data.length;
    count++;
    const b64 = data.toString('base64');
    lines.push(`@font-face {
  font-family: '${font.family}';
  font-style: ${font.style};
  font-display: swap;
  font-weight: ${font.weight};
  src: url(data:font/woff2;base64,${b64}) format('woff2');
}`);
  }

  const totalB64 = Math.round(totalRaw * 4 / 3);
  console.log(`  Fonts: ${count} faces, ${totalRaw} bytes raw, ~${totalB64} bytes base64`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Icon sprite: generate <symbol> elements from the heroicons npm package
// ---------------------------------------------------------------------------
const OUTLINE_ATTRS = 'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"';
const SOLID_ATTRS = 'viewBox="0 0 24 24" fill="currentColor" stroke="none"';
const CHEVRON_ATTRS = 'viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"';

const ICON_MAP: Array<{ id: string; file: string; variant?: 'solid' | 'chevron' }> = [
  { id: 'i-backward', file: 'backward.svg' },
  { id: 'i-bars', file: 'bars-3.svg' },
  { id: 'i-book', file: 'book-open.svg' },
  { id: 'i-calendar', file: 'calendar.svg' },
  { id: 'i-chevron-down', file: 'chevron-down.svg', variant: 'chevron' },
  { id: 'i-chevron-left', file: 'chevron-left.svg', variant: 'chevron' },
  { id: 'i-chevron-right', file: 'chevron-right.svg', variant: 'chevron' },
  { id: 'i-chevron-up', file: 'chevron-up.svg', variant: 'chevron' },
  { id: 'i-cloud-download', file: 'cloud-arrow-down.svg' },
  { id: 'i-comment', file: 'chat-bubble-oval-left-ellipsis.svg' },
  { id: 'i-ellipsis', file: 'ellipsis-horizontal.svg' },
  { id: 'i-envelope', file: 'envelope.svg' },
  { id: 'i-external', file: 'arrow-top-right-on-square.svg' },
  { id: 'i-eye-slash', file: 'eye-slash.svg' },
  { id: 'i-focus', file: 'bars-2.svg' },
  { id: 'i-forward', file: 'forward.svg' },
  { id: 'i-gear', file: 'cog-6-tooth.svg' },
  { id: 'i-globe', file: 'globe-alt.svg' },
  { id: 'i-heart', file: 'heart.svg', variant: 'solid' },
  { id: 'i-heart-o', file: 'heart.svg' },
  { id: 'i-home', file: 'home.svg' },
  { id: 'i-inbox', file: 'inbox.svg' },
  { id: 'i-link', file: 'link.svg' },
  { id: 'i-mic', file: 'microphone.svg' },
  { id: 'i-pause', file: 'pause.svg' },
  { id: 'i-pen', file: 'pencil.svg' },
  { id: 'i-pin', file: 'map-pin.svg' },
  { id: 'i-play', file: 'play.svg' },
  { id: 'i-plus', file: 'plus.svg', variant: 'chevron' },
  { id: 'i-queue', file: 'queue-list.svg' },
  { id: 'i-refresh', file: 'arrow-path.svg' },
  { id: 'i-search', file: 'magnifying-glass.svg' },
  { id: 'i-share', file: 'arrow-up-tray.svg' },
  { id: 'i-sliders', file: 'adjustments-horizontal.svg' },
  { id: 'i-squares', file: 'squares-2x2.svg' },
  { id: 'i-stop', file: 'stop.svg' },
  { id: 'i-tags', file: 'tag.svg' },
  { id: 'i-volume', file: 'speaker-wave.svg' },
  { id: 'i-wand', file: 'sparkles.svg' },
  { id: 'i-xmark', file: 'x-mark.svg' },
];

function extractSvgInner(svgContent: string): string {
  return svgContent
    .replace(/<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
}

function generateIconSymbols(): string {
  const heroiconsDir = join(rootDir, 'node_modules', 'heroicons', '24');
  const symbols: string[] = [];

  for (const icon of ICON_MAP) {
    const dir = icon.variant === 'solid' ? 'solid' : 'outline';
    const filepath = join(heroiconsDir, dir, icon.file);
    if (!existsSync(filepath)) {
      console.warn(`  Warning: heroicon not found: ${dir}/${icon.file}`);
      continue;
    }
    const inner = extractSvgInner(readFileSync(filepath, 'utf-8'));
    let attrs: string;
    if (icon.variant === 'solid') attrs = SOLID_ATTRS;
    else if (icon.variant === 'chevron') attrs = CHEVRON_ATTRS;
    else attrs = OUTLINE_ATTRS;
    symbols.push(`  <symbol id="${icon.id}" ${attrs}>${inner}</symbol>`);
  }

  console.log(`  Icons: ${symbols.length} symbols generated from heroicons package`);
  return symbols.join('\n');
}

// ---------------------------------------------------------------------------
// Build the embedded HTML
// ---------------------------------------------------------------------------
let html = readFileSync(htmlPath, 'utf-8');
const css = readFileSync(cssPath, 'utf-8');

// Read JS modules from viewer/ directory in sorted order (01-state.js, 02-utils.js, etc.)
const jsFiles = readdirSync(jsDir).filter(f => f.endsWith('.js')).sort();
const jsModules = jsFiles.map(f => readFileSync(join(jsDir, f), 'utf-8'));
const js = jsModules.join('\n');

// Generate font @font-face CSS and prepend to the main CSS
const fontCss = generateFontCSS();

// Generate icon sprite symbols from heroicons package
const iconSymbols = generateIconSymbols();

// Inline icons, CSS (with fonts prepended), and JS into the HTML template
html = html.replace('<!-- INJECT:ICONS -->', () => iconSymbols);
html = html.replace('/* INJECT:CSS */', () => fontCss + '\n' + css);
html = html.replace('/* INJECT:JS */', () => js);

// JSON.stringify safely escapes all special characters (quotes, newlines,
// backslashes, unicode, angle brackets, template literals, etc.)
const source = [
  '// Auto-generated by scripts/embed-viewer.ts — do not edit',
  '// Source: viewer.html + viewer.css + viewer/*.js + @fontsource/* woff2',
  `export const VIEWER_HTML = ${JSON.stringify(html)};`,
  '',
].join('\n');

writeFileSync(outPath, source);
const moduleList = jsFiles.map(f => `  ${f} (${readFileSync(join(jsDir, f), 'utf-8').length} bytes)`).join('\n');
console.log(`Embedded viewer (${html.length} bytes) into src/viewer-html.ts`);
console.log(`  HTML template: ${readFileSync(htmlPath, 'utf-8').length} bytes`);
console.log(`  CSS: ${css.length} bytes (before font injection)`);
console.log(`  JS modules (${jsFiles.length} files, ${js.length} bytes total):\n${moduleList}`);
