// ABOUTME: Pre-build script that embeds viewer.html + viewer.css + viewer.js into a TypeScript module
// ABOUTME: Reads the three source files and inlines CSS/JS into the HTML template

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';

const rootDir = join(dirname(process.argv[1]), '..');
const htmlPath = join(rootDir, 'viewer.html');
const cssPath = join(rootDir, 'viewer.css');
const jsPath = join(rootDir, 'viewer.js');
const outPath = join(rootDir, 'src', 'viewer-html.ts');

let html = readFileSync(htmlPath, 'utf-8');
const css = readFileSync(cssPath, 'utf-8');
const js = readFileSync(jsPath, 'utf-8');

// Inline CSS and JS into the HTML template at the marker positions
html = html.replace('/* INJECT:CSS */', css);
html = html.replace('/* INJECT:JS */', js);

// JSON.stringify safely escapes all special characters (quotes, newlines,
// backslashes, unicode, angle brackets, template literals, etc.)
const source = [
  '// Auto-generated by scripts/embed-viewer.ts — do not edit',
  '// Source: viewer.html + viewer.css + viewer.js',
  `export const VIEWER_HTML = ${JSON.stringify(html)};`,
  '',
].join('\n');

writeFileSync(outPath, source);
console.log(`Embedded viewer (${html.length} bytes: html=${readFileSync(htmlPath, 'utf-8').length}, css=${css.length}, js=${js.length}) into src/viewer-html.ts`);
