// ABOUTME: Pre-build script that embeds viewer.html + viewer.css + viewer/*.js into a TypeScript module
// ABOUTME: Reads the HTML template, CSS, JS modules, and font woff2 files, inlines everything into a single HTML string

import { readFileSync, writeFileSync, readdirSync, existsSync } from 'fs';
import { join, dirname } from 'path';

const rootDir = join(dirname(process.argv[1]), '..');
const htmlPath = join(rootDir, 'viewer.html');
const cssPath = join(rootDir, 'viewer.css');
const jsDir = join(rootDir, 'viewer');
const outPath = join(rootDir, 'src', 'viewer-html.ts');

// ---------------------------------------------------------------------------
// Font embedding: self-host fonts as base64 data URIs for offline support
// All fonts are SIL Open Font License 1.1 — legal to bundle and redistribute
// ---------------------------------------------------------------------------
const FONTS: Array<{ family: string; pkg: string; weight: number; style: string }> = [
  // Inter (UI font for settings, sidebar, controls)
  { family: 'Inter', pkg: 'inter', weight: 400, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 500, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 600, style: 'normal' },
  { family: 'Inter', pkg: 'inter', weight: 700, style: 'normal' },
  // Literata (reading font option)
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 700, style: 'normal' },
  { family: 'Literata', pkg: 'literata', weight: 400, style: 'italic' },
  // Lora (reading font option)
  { family: 'Lora', pkg: 'lora', weight: 400, style: 'normal' },
  { family: 'Lora', pkg: 'lora', weight: 700, style: 'normal' },
  { family: 'Lora', pkg: 'lora', weight: 400, style: 'italic' },
  // Source Serif 4 (reading font option)
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 400, style: 'normal' },
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 700, style: 'normal' },
  { family: 'Source Serif 4', pkg: 'source-serif-4', weight: 400, style: 'italic' },
  // Work Sans (primary UI font + reading font option)
  { family: 'Work Sans', pkg: 'work-sans', weight: 400, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 500, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 600, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 700, style: 'normal' },
  { family: 'Work Sans', pkg: 'work-sans', weight: 400, style: 'italic' },
  // Instrument Serif (title font for pairings)
  { family: 'Instrument Serif', pkg: 'instrument-serif', weight: 400, style: 'normal' },
  { family: 'Instrument Serif', pkg: 'instrument-serif', weight: 400, style: 'italic' },
  // OpenDyslexic (accessibility reading font)
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 400, style: 'normal' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 700, style: 'normal' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 400, style: 'italic' },
  { family: 'OpenDyslexic', pkg: 'opendyslexic', weight: 700, style: 'italic' },
];

function generateFontCSS(): string {
  const lines: string[] = ['/* Self-hosted fonts (all SIL OFL 1.1) — generated by embed-viewer.ts */'];
  let totalRaw = 0;
  let count = 0;

  for (const font of FONTS) {
    const filename = `${font.pkg}-latin-${font.weight}-${font.style}.woff2`;
    const filepath = join(rootDir, 'node_modules', '@fontsource', font.pkg, 'files', filename);
    if (!existsSync(filepath)) {
      console.warn(`  Warning: font file not found: ${filename} (run bun install)`);
      continue;
    }
    const data = readFileSync(filepath);
    totalRaw += data.length;
    count++;
    const b64 = data.toString('base64');
    lines.push(`@font-face {
  font-family: '${font.family}';
  font-style: ${font.style};
  font-display: swap;
  font-weight: ${font.weight};
  src: url(data:font/woff2;base64,${b64}) format('woff2');
}`);
  }

  const totalB64 = Math.round(totalRaw * 4 / 3);
  console.log(`  Fonts: ${count} faces, ${totalRaw} bytes raw, ~${totalB64} bytes base64`);
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Build the embedded HTML
// ---------------------------------------------------------------------------
let html = readFileSync(htmlPath, 'utf-8');
const css = readFileSync(cssPath, 'utf-8');

// Read JS modules from viewer/ directory in sorted order (01-state.js, 02-utils.js, etc.)
const jsFiles = readdirSync(jsDir).filter(f => f.endsWith('.js')).sort();
const jsModules = jsFiles.map(f => readFileSync(join(jsDir, f), 'utf-8'));
const js = jsModules.join('\n');

// Generate font @font-face CSS and prepend to the main CSS
const fontCss = generateFontCSS();

// Inline CSS (with fonts prepended) and JS into the HTML template
html = html.replace('/* INJECT:CSS */', () => fontCss + '\n' + css);
html = html.replace('/* INJECT:JS */', () => js);

// JSON.stringify safely escapes all special characters (quotes, newlines,
// backslashes, unicode, angle brackets, template literals, etc.)
const source = [
  '// Auto-generated by scripts/embed-viewer.ts — do not edit',
  '// Source: viewer.html + viewer.css + viewer/*.js + @fontsource/* woff2',
  `export const VIEWER_HTML = ${JSON.stringify(html)};`,
  '',
].join('\n');

writeFileSync(outPath, source);
const moduleList = jsFiles.map(f => `  ${f} (${readFileSync(join(jsDir, f), 'utf-8').length} bytes)`).join('\n');
console.log(`Embedded viewer (${html.length} bytes) into src/viewer-html.ts`);
console.log(`  HTML template: ${readFileSync(htmlPath, 'utf-8').length} bytes`);
console.log(`  CSS: ${css.length} bytes (before font injection)`);
console.log(`  JS modules (${jsFiles.length} files, ${js.length} bytes total):\n${moduleList}`);
